### PR TITLE
Issue# 1182 - Integrate Defense Matrix Sabotage Fix to CHL

### LINKED ISSUE #1182: Integrate Defense Matrix Sabotage Fix
https://steamcommunity.com/sharedfiles/filedetails/?id=1135867452

Another bugfix that arguably should be integrated into Highlander.

### PR DESCRIPTION
**Pull request by BlackDog86**
Fixes #1182 

Adds the relevant code from Sabotage fix mod directly to X2StrategyElement_XpackChosenActions

### CODE REVIEW

**Review by Iridar — CHANGES_REQUESTED** [review]
I would do it like this:

```
static private function int GetSabotageChance(XComGameState_AdventChosen ChosenState)
{	
	// Variables for Issue #1182
	local XComGameState_HeadquartersXCom XComHQ;
	local int DefenseMatrixSabotageChanceModifier;
	
	// Start Issue #1182
	/// HL-Docs: ref:Bugfixes; issue:1182
	/// Make Defense Matrix properly reduce the chance of Chosen sabotage.
	XComHQ = XComGameState_HeadquartersXCom(`XCOMHISTORY.GetSingleGameStateObjectForClass(class'XComGameState_HeadquartersXCom', true));
	if (XComHQ != none)
	{
		DefenseMatrixSabotageChanceModifier = XComHQ.SabotageChanceModifier;
	}
	
	return `ScaleStrategyArrayInt(class'X2StrategyElement_XpackChosenActions'.default.SabotageChance) + DefenseMatrixSabotageChanceModifier;
	// End Issue #1182
}
```

As a general rule, if code changes involve more than one line, use Start / End Issue tags. 

And this is a bit anal, but from my experience, obsessive none-checking does more good than harm in the long run.

And finally, for bugfixes we use `/// HL-Docs: ref:Bugfixes; issue:####` tags, if the bugfix is simple enough to be summarized in one-two sentences.

**Comment by BlackDog86** [comment]
Yeah that code is definitely a bit cleaner-looking - I just wholesale took the function from the base mod as-is. 

I didn't think to none-check the HQ to be fair, good shout.

**Comment by Iridar** [comment]
> Yeah that code is definitely a bit cleaner-looking - I just wholesale took the function from the base mod as-is.
> 
> I didn't think to none-check the HQ to be fair, either, good shout.

To be fair, if there's no XComHQ in History, the player has bigger problems than an "accessed none" warning, but this is more the general principle. I've legitimately had cases where lazying out on none-checks caused serious bugs.

**Review by Iridar — APPROVED** [review]
Tentatively approved, TODO before merging: trace code and ideally run some tests.

**Pull request merged**
