### PR TITLE
#424 Add Greater Control for Gremlin "Ghosts" in Staffslots - Attempt 2

### PR DESCRIPTION
**Pull request by VampireMonkey**
Should work now.

### CODE REVIEW

**Comment by VampireMonkey** [comment]
I'm not very good at this

**Comment by pledbrook** [comment]
@VampireMonkey The OnSortFinished change shouldn't be in this pull request I take it?

**Comment by Xymanek** [comment]
The `Helper` doesn't seem to be in use... Is it needed?

**Comment by VampireMonkey** [comment]
Imma try this again

**Pull request closed without merging**
