### PR TITLE
Chosen Death Teleport Visualization Fix

### LINKED ISSUE #496: Chosen death teleport effect times out
image

Happens to me always when running with redscreens

### PR DESCRIPTION
**Pull request by BlackDog86**
Fixes #496 - Tested & confirmed working with minimal code changes.

### CODE REVIEW

**Comment by Iridar** [comment]
What's the status here? Is this ready for review?

**Comment by BlackDog86** [comment]
Yep, all good - I've tested it a few ways with different abilities and it seems to work just fine :)

**Comment by Iridar** [comment]
Uhh why is X2Ability_CarryUnit in this PR?

**Comment by Iridar** [comment]
Good thing I decided to test this before merging, because current implementation is causing bugged visualization.

https://youtu.be/va8IXk38H7Y

The Chosen plays a part of the standard rifle shot animation before teleporting away. Also it seems to be overlaid on top of the chosen death animation, because it horribly distorts his chest and shoulders. 

I don't know why exactly does this happen, but implementing a different solution should bypass the problem.

**Comment by Iridar** [comment]
Since the original issue happens because the particle effect `"FX_Chosen_Teleport.P_Chosen_Teleport_Out_w_Sound"` never finishes playing, presumably because that's just how it is set up, there are two possible solutions here:

1. Create an alternative effect that *will* finish playing, allowing visualization to proceed as intended.
2. Create an `X2Action_TimedWait` that runs in parallel to the `X2Action_PlayEffect`, and make actions that previously waited on `X2Action_PlayEffect` wait on `X2Action_TimedWait` instead. Give it ~5 seconds or so.

**Comment by Iridar** [comment]
On deeper look, it seems that build visualization function is just a horrible bugged mess.

**Comment by Iridar** [comment]
So the firing animation was played by the build visualization function itself for no adequate reason. Once I got rid of that and tweaked the build vis in a few places, it's crispy smooth:

https://youtu.be/kv-MRWrBGcQ

**Comment by Iridar** [comment]
I ended up refactoring most of the build visualization function for that ability. The original one was horribly defunct, and the only reason it was working at all is because the thing that was breaking it was broken as well. 

It appears it tried to play the Chosen weapon firing animation at the same time as the death animation was playing, and treated the animation action as if it *was* the death animation.

At least that's the only way I can make sense of it at all. 

Either way, I removed the animation action and added a couple delays to make sure it visualizes in a decent manner. 

According to testing by Black Dog, the actual delay tends to vary depending on how exactly the Chosen was killed, e.g. kills by melee or environmental explosive will have different timings.

Ideally I would want to have an X2Action that waits for the pawn to become fully idle before the teleport visualization can start, regardless of the death animation used, but there's no existing methodology for that, and would require bigger scope of Highlander changes that I'm comfortable with.

So I'll leave this as is for now, revisit it later if there are any complaints.

**Pull request merged**
