### PR TITLE
Fix AllTargetStylesNative detection

### LINKED ISSUE #1019: Script targeting style detection is too overzealous
https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/blob/84ae0e3b34458d45b968f0893d0c3d3ae238907f/X2WOTCCommunityHighlander/Src/XComGame/Classes/X2AbilityTemplate.uc#L257-L283

I've added a bit of logging:

```uc
`log("Instantiating XComGameState_Ability_CH for" @ DataName,, 'CH_ScriptTargetStyle');
Ability = XComGameState_Ability(NewGameState.CreateNewStateObject(class'XComGameState_Ability_CH', self));
```

Result is a bit more than one would expect: https://gist.github.com/Xymanek/7d568340cb4811e8e64e5ccd50cd72d5

cc @robojumper as the author of the latest implementation (#918)

### PR DESCRIPTION
**Pull request by robojumper**
Fixes #1019.

### CODE REVIEW

**Comment by robojumper** [comment]
I'm 99% sure this is the correct fix but I haven't tested it.

**Review by Xymanek — COMMENTED** [review]
Can confirm that the replacement is no longer used when it's not needed.

However, I do not have a test case for when the replacement is actually needed.

**Comment by Iridar** [comment]
I have a test case for this, I'll see about getting this tested.

**Review by Iridar — APPROVED** [review]
I've tested and can confirm it's working as intended for abilities with custom multi target styles.

**Comment by Iridar** [comment]
Perhaps I can use this as an opportunity to merge something? How do I proceed, just merge the PR with the default merge message?

**Pull request merged**
