### PR TITLE
Cache hit chance when sorting the list of potential targets in tactical and ensure the sorted order matches the order of TAB-cycling

### LINKED ISSUE #1233: UITacticalHUD_Enemies UpdateVisibleEnemies should use cached hit chances when sorting final targets array
UpdateVisibleEnemies of UITacticalHUD_Enemies sorts the array of visible enemies by hit chance using a comparer delegate.

This sorting delegate determines the hit change, by calling GetHitChanceForObjectRef on object A and B, which is relatively slow, and calls it multiple times for the same objects, until the array is fully sorted.

The hit chance for the same object reference cannot change during one sorting pass, so pre-calculating the hit chances for visible enemies first. Then using that in the sorting delegate would decrease the number of calls drastically.

Before:
image

After:
image

Note that I used the override of UITacticalHUD_Enemies from 'WOTC_DisplayHitChange' to do my test, which was easier for now than to build a custom CHL.

The profiling was done on the exact same save, same conditions, same move. Reduced the number of calls in that one frame, from 378 to 48.

```
struct StateObjectReferenceWrapper
{
	var StateObjectReference Object;
	var int HitChance;
};

simulated function UpdateVisibleEnemies(int HistoryIndex)
{
	local array<StateObjectReferenceWrapper> CachedHitChanges;
	local StateObjectReferenceWrapper HitChangeWrapper;

	// ... snip

	if (kActiveUnit != none)
	{
		// ... snip

		iNumVisibleEnemies = m_arrTargets.Length;

		CachedHitChanges.Length = 0;
		for (i = 0; i < m_arrTargets.Length; ++i)
		{
			HitChangeWrapper.Object = m_arrTargets[i];
			HitChangeWrapper.HitChance = GetHitChanceForObjectRef(HitChangeWrapper.Object);
			CachedHitChanges.AddItem(HitChangeWrapper);
		}

		CachedHitChanges.Sort(SortEnemies2);

		m_arrTargets.Length = 0;
		for (i = 0; i < CachedHitChanges.Length; ++i)
		{
			m_arrTargets.AddItem(CachedHitChanges[i].Object);
		}

		UpdateVisuals(HistoryIndex);
	}
}

private function int SortEnemies2(StateObjectReferenceWrapper ObjectA, StateObjectReferenceWrapper ObjectB)
{
    // you get the point :)
}	
```

Not sure if the above implementation is ideal, that's the best I could do with my limited UnrealScript knowledge.
Maybe it's also possible with a class variable, then using CachedHitChanges.Find('Object', ObjectA) (which is a hashtable lookup?) inside SortEnemies.

discord: https://discord.com/channels/165245941664710656/165245941664710656/1137333029837209630

### PR DESCRIPTION
**Pull request by Iridar**
Fixes #1233
Alternative implementation of #1234 

Differences: moved the sorting into a separate function, added some code to fix the "bug" where the order of TAB-cycling through targets does not always the match the order of displayed target icons for targets that have the same hit chance. 

I separated them into two commits so that the TAB-cycling functionality is easier to see during the review.

I added HL-Docs for this issue as if it's a bugfix, not sure how correct is that, but I figured there's nothing about this change that needs to be mod-dev facing, as it's mostly an optimization change.

### CODE REVIEW

**Comment by Iridar** [comment]
Tested in lab conditions, tutorial, and first mission afterwards. Seems to work fine.

**Comment by Iridar** [comment]
This needs testing with various targetable interactive objects, such as explosive barrels and psi nodes on the Sabotage Psi Emitter mission. Make sure the order of displayed icons matches the order of clicking on the icon or using an ability to enter targeting.

**Comment by BlackDog86** [comment]
I can have a go at checking this out

**Comment by Iridar** [comment]
Would be appreciated

**Comment by BlackDog86** [comment]
OK so this all looks good to me - I tested with the psionic transmitter nodes, an alien relay and a couple other destructables - each time the destructables were sorted to the end of the the targetting array & I didn't get any instances where clicking on a target took me to the wrong unit or anything weird like that. Even the hacking preview appears to keep the units in the correct hit chance order (obviously excluding units that are irrelevant for hacking) so I'm pretty confident this is working. I can't really think of many edge-case destructables that might not behave in the same way as the rest either but if you can think of any more I'm happy to give them a trial before we sign this one off.

**Comment by Iridar** [comment]
Thank you, I think this is good to go.

**Pull request merged**
