### PR TITLE
Fix for #313, broken GetStatModifiers()

### PR DESCRIPTION
**Pull request by MrNiceUK**
#313

### CODE REVIEW

**Comment by Musashi1584** [comment]
Can this be potentially merged? If so why hasn't it already been merged?

**Comment by MrNiceUK** [comment]
Reason why it hasn't already? Closest to an answer:
https://discordapp.com/channels/165245941664710656/273238884433788928/506778534929367043

**Comment by Xymanek** [comment]
The repercussions of possible/accidental mis-implementation in this will disastrous. I would argue that this needs very through testing, much more thorough than most others CHL features

**Comment by MrNiceUK** [comment]
Well it's had 6 months for someone other than me to actually test it in....

**Pull request closed without merging**
