### PR TITLE
Fix "accessed none" log warning

### PR DESCRIPTION
**Pull request by Iridar**
Tracking Issue #324

For now this PR simply fixes one "accessed none" log warning for FactionState in UISoldierHeader.

### CODE REVIEW

**Comment by Iridar** [comment]
Added a bunch of other log warning fixes.

**Comment by Iridar** [comment]
More log warnings for the log warning god:
```
[0293.06] ScriptWarning: Accessed None
	X2TacticalGameRuleset Plot_WLD_ATT_Ravine.TheWorld:PersistentLevel.X2TacticalGameRuleset_2
	Function XComGame.X2TacticalGameRuleset:EndTacticalGame.IsLostAndAbandonedMission:00C5

[0284.01] ScriptWarning: Accessed None 'MissionSource'
	XComGameState_BattleData Transient.XComEngine_0:XComGameStateHistory_0.XComGameState_3073.XComGameState_BattleData_105
	Function XComGame.XComGameState_BattleData:SetVictoriousPlayer:00B9

[0284.01] ScriptWarning: Accessed array 'X2MissionNarrativeTemplate_34.ConsoleObjectiveTextPools' out of bounds (1/0)
	X2MissionNarrativeTemplate Transient.X2MissionNarrativeTemplate_34
	Function XComGame.X2MissionNarrativeTemplate:GetObjectiveText:0132

[0275.58] ScriptWarning: Accessed None 'bIsChosen'
	XComGameStateContext_TacticalGameRule Transient.XComEngine_0:XComGameStateHistory_0.XComGameState_2907.XComGameStateContext_TacticalGameRule_177
	Function XComGame.XComGameStateContext_TacticalGameRule:BuildPlayerTurnBeginVisualization:0189

[0274.36] ScriptWarning: Accessed array 'UIObjectiveList_2.Items' out of bounds (0/0)
	UIObjectiveList Plot_WLD_ATT_Ravine.TheWorld:PersistentLevel.UIObjectiveList_2
	Function XComGame.UIObjectiveList:ClearList:003B
[0274.36] ScriptWarning: Accessed None 'Items'
	UIObjectiveList Plot_WLD_ATT_Ravine.TheWorld:PersistentLevel.UIObjectiveList_2
	Function XComGame.UIObjectiveList:ClearList:003B
[0274.36] ScriptWarning: Accessed array 'UIObjectiveList_2.Items' out of bounds (2/2)
	UIObjectiveList Plot_WLD_ATT_Ravine.TheWorld:PersistentLevel.UIObjectiveList_2
	Function XComGame.UIObjectiveList:ClearList:003B
[0274.36] ScriptWarning: Accessed None 'Items'
	UIObjectiveList Plot_WLD_ATT_Ravine.TheWorld:PersistentLevel.UIObjectiveList_2
	Function XComGame.UIObjectiveList:ClearList:003B

[0273.94] ScriptWarning: Accessed array 'X2MissionNarrativeTemplate_34.ConsoleObjectiveTextPools' out of bounds (1/0)
	X2MissionNarrativeTemplate Transient.X2MissionNarrativeTemplate_34
	Function XComGame.X2MissionNarrativeTemplate:GetObjectiveText:0132
[0273.94] ScriptWarning: Accessed array 'X2MissionNarrativeTemplate_34.ConsoleObjectiveTextPools' out of bounds (0/0)
	X2MissionNarrativeTemplate Transient.X2MissionNarrativeTemplate_34
	Function XComGame.X2MissionNarrativeTemplate:GetObjectiveText:0132

[0272.74] Warning: USkeletalMeshComponent::InitArticulated : No PhysicsAsset defined for Plot_WLD_ATT_Ravine.TheWorld:PersistentLevel.XComWeapon_116.SkeletalMeshComponent_1928 with skeletalmesh FX_Weapons_Shared.Weapon_Dummy

[0272.66] ScriptWarning: Accessed None 'kOwner'
	XGWeapon Plot_WLD_ATT_Ravine.TheWorld:PersistentLevel.XGWeapon_109
	Function XComGame.XGWeapon:CreateEntity:0257

[0272.63] ScriptWarning: Accessed None 'UnitState'
	X2WeaponTemplate Transient.X2WeaponTemplate_24
	Function XComGame.X2WeaponTemplate:DetermineGameArchetypeForUnit:01A0

[0271.49] ScriptWarning: Accessed None 'ObjectID'
	X2TacticalGameRuleset Plot_WLD_ATT_Ravine.TheWorld:PersistentLevel.X2TacticalGameRuleset_2
	Function XComGame.X2TacticalGameRuleset:CreateTacticalGame.StartStateSpawnAliens:0382
[0271.49] ScriptWarning: Accessed None 'CosmeticUnit'
	XComGameState_Item Transient.XComEngine_0:XComGameStateHistory_0.XComGameState_2758.XComGameState_Item_2198
	Function XComGame.XComGameState_Item:CreateCosmeticItemUnit:0444

[0194.14] ScriptWarning: Accessed None 'NewProjectile'
	XGUnit Plot_CTY_Vehicle_Plaza.TheWorld:PersistentLevel.XGUnit_21
	Function XComGame.XGUnitNativeBase:SpawnAndConfigureNewProjectile:00CA
[0194.14] ScriptWarning: Accessed None 'ProjectileTemplate'
	XGUnit Plot_CTY_Vehicle_Plaza.TheWorld:PersistentLevel.XGUnit_21
	Function XComGame.XGUnitNativeBase:SpawnAndConfigureNewProjectile:0059

[0280.24] ScriptWarning: Accessed None 'UpgradeTemplate'
    XComGameState_LadderProgress XComGame.Default__XComGameState_LadderProgress
    Function XComGame.XComGameState_LadderProgress:MaybeTweakItemName:01CD
```

**Comment by Iridar** [comment]
And more 
```
[0284.93] ScriptWarning: Accessed None 'utilItems'
	UITLE_SkirmishModeMenu XPACK_Shell_Xenoform.TheWorld:PersistentLevel.UITLE_SkirmishModeMenu_0
	Function XComGame.UITLE_SkirmishModeMenu:SetSoldierGear:0697
```

**Comment by Iridar** [comment]
Morer
```
[0148.45] ScriptWarning: Accessed None 'EquippedItem'
	UITLEUnitStats Plot_ABN_Expedition_Waterfront.TheWorld:PersistentLevel.UITLEUnitStats_1
	Function XComGame.UITLEUnitStats:PopulateSoldierGear:0710
```

**Comment by Iridar** [comment]
Morerer
```
[0089.90] ScriptWarning: Accessed array 'XComPerkContentInst_3.m_TargetDurationMITVs' out of bounds (0/0)
	XComPerkContentInst Plot_TWN_GOps_TrainYard_02.TheWorld:PersistentLevel.XComPerkContentInst_3
	Function XComGame.XComPerkContentInst:DurationActive.EndState:03F8
[0089.90] ScriptWarning: Accessed array 'XComPerkContentInst_3.m_TargetDurationEndMITVs' out of bounds (0/0)
	XComPerkContentInst Plot_TWN_GOps_TrainYard_02.TheWorld:PersistentLevel.XComPerkContentInst_3
	Function XComGame.XComPerkContentInst:DurationActive.EndState:04CF
[0091.39] ScriptWarning: Accessed None
	XComAlienPawn Plot_TWN_GOps_TrainYard_02.TheWorld:PersistentLevel.XComAlienPawn_10
	Function XComGame.XComUnitPawnNativeBase:Helper_EnableRMARotation:00E4
[0096.61] ScriptWarning: Accessed None 'CreatedPawn'
	X2Action_RevealAIBegin Plot_TWN_GOps_TrainYard_02.TheWorld:PersistentLevel.X2Action_RevealAIBegin_0
	Function XComGame.X2Action_PlayMatinee:RemoveUnitsFromMatinee:01E5
```

**Comment by Iridar** [comment]
And more:
```
[0205.97] ScriptWarning: Accessed array 'UITacticalHUD_AbilityContainer_1.AvailableTargets' out of bounds (0/0)
	UITacticalHUD_AbilityContainer Plot_ABN_Sabotage_ElTrain.TheWorld:PersistentLevel.UITacticalHUD_AbilityContainer_1
	Function XComGame.UITacticalHUD_AbilityContainer:ConfirmAbility:032B
[0205.99] ScriptWarning: Accessed array 'XComGameStateContext_Ability_646.MultiTargets' out of bounds (3/3)
	XComGameStateContext_Ability Transient.XComGameStateContext_Ability_646
	Function XComGame.XComGameStateContext_Ability:AbilityPostActivationUpdates:0803
[0205.99] ScriptWarning: Accessed array 'XComGameStateContext_Ability_646.MultiTargets' out of bounds (3/3)
	XComGameStateContext_Ability Transient.XComGameStateContext_Ability_646
	Function XComGame.XComGameStateContext_Ability:AbilityPostActivationUpdates:08A1
```

**Comment by Xymanek** [comment]
Postponing on author's request

**Comment by Iridar** [comment]
This PR got overly ambitious and I got cold feet, so this never ended up merged. Some of these log warnings were fixed by #1226, the rest can still be fixed eventually.

**Pull request closed without merging**
