### PR TITLE
Allow mods to set rulers to wait on specific missions

### LINKED ISSUE #771: Remove XPack integration check in XCGS_AlienRulerManager GetRulerLocatedAtMission
```uc
private function StateObjectReference GetRulerLocatedAtMission(XComGameState_MissionSite MissionState)
{
	local AlienRulerLocation RulerLocation;

	// If DLC is integrated with the XPack, rulers only appear for the first time on specific missions
	if (class'X2Helpers_DLC_Day60'.static.IsXPackIntegrationEnabled())
	{
		// Check to see if the ruler is located at this mission site
		foreach AlienRulerLocations(RulerLocation)
		{
			if (RulerLocation.MissionRef.ObjectID == MissionState.ObjectID)
			{
				return RulerLocation.RulerRef;
			}
		}
	}
}
```

The check is useless as without the xpack integration enabled `AlienRulerLocations` will never be populated. Removing it, however, will allow mods to use `AlienRulerLocations` to make certain rulers "wait" on certain missions

### PR DESCRIPTION
**Pull request by Xymanek**
Closes #771 

This PR removes the old separate-component-based DLC CHL approach. It was confirmed that if one doesn't own DLC2, the replacement package doesn't load, as such I decided to ship it together with main CHL for better player UX. Log comparison:

```
[0013.04] Log: X2WOTCCommunityHighlander: Creating CHXCOMGameVersionTemplate...
[0013.04] Log: X2WOTCCommunityHighlander: Created CHXCOMGameVersionTemplate with version 1.20.0
[0013.04] Log: X2WOTCCommunityHighlander: Creating Engine version template...
[0013.04] Log: X2WOTCCommunityHighlander: Created Engine version template with version 1.20.0
[0013.53] DLC2CommunityHighlander: CreateTemplates
[0013.53] DLC2CommunityHighlander: Creating CHDLC2Version with version 1.20.0
[0015.16] X2WOTCCommunityHighlander: Companion script package loaded
[0015.16] X2WOTCCommunityHighlander: Components:
```
```
[0035.83] Log: X2WOTCCommunityHighlander: Creating CHXCOMGameVersionTemplate...
[0035.83] Log: X2WOTCCommunityHighlander: Created CHXCOMGameVersionTemplate with version 1.20.0
[0035.83] Log: X2WOTCCommunityHighlander: Creating Engine version template...
[0035.83] Log: X2WOTCCommunityHighlander: Created Engine version template with version 1.20.0
[0037.54] X2WOTCCommunityHighlander: Companion script package loaded
[0037.54] X2WOTCCommunityHighlander: Components:
```

Possible conflicts:

* Another mod ships `DLC_2.u`. Don't think we can do much here but I also don't think this is the case
* Some mod does `+NonNativePackages=DLC_2` in config. I think it's safe to assume that such mod will have DLC2 in the requirements list and thus not installed by non-DLC2-owners

@robojumper plz review. I suggest looking at individual commits for easier understanding of what's happening

TODO:
* [x] Docs (if this approach is approved)
* [x] Shell info (pending decision on #765)

### CODE REVIEW

**Comment by Xymanek** [comment]
@ robo's comment:
 image

**Comment by Xymanek** [comment]
image

```
[0023.38] X2WOTCCommunityHighlander: Companion script package loaded
[0023.39] X2WOTCCommunityHighlander: Components:
[0023.39] X2WOTCCommunityHighlander:   X2WOTCCommunityHighlander -- v1.20.0 (faf519)
[0023.39] X2WOTCCommunityHighlander:   Engine -- v1.20.0 (faf519)
[0023.39] X2WOTCCommunityHighlander:   XComGame -- v1.20.0 (faf519)
[0023.39] X2WOTCCommunityHighlander:   DLC_2 -- v1.20.0 (faf519)
```

image

```
[0023.65] X2WOTCCommunityHighlander: Companion script package loaded
[0023.66] X2WOTCCommunityHighlander: Components:
[0023.66] X2WOTCCommunityHighlander:   X2WOTCCommunityHighlander -- v1.20.0 (faf519)
[0023.66] X2WOTCCommunityHighlander:   Engine -- v1.20.0 (faf519)
[0023.67] X2WOTCCommunityHighlander:   XComGame -- v1.20.0 (faf519)
[0023.67] X2WOTCCommunityHighlander:   DLC_2 -- NOT LOADED - REQUIRED
[0023.67] X2WOTCCommunityHighlander: Required packages were not loaded. Please consult https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/wiki/Troubleshooting for further information
```

We may need to also add something to this part (where? OPTC? CreateTemplates?):

```
[0020.13] Log: X2WOTCCommunityHighlander: Creating CHXCOMGameVersionTemplate...
[0020.13] Log: X2WOTCCommunityHighlander: Created CHXCOMGameVersionTemplate with version 1.20.0
[0020.14] Log: X2WOTCCommunityHighlander: Creating Engine version template...
[0020.14] Log: X2WOTCCommunityHighlander: Created Engine version template with version 1.20.0
```

**Comment by Xymanek** [comment]
I think that would be more suitable for a separate PR

**Comment by robojumper** [comment]
... modulo Docs.

**Comment by Xymanek** [comment]
@robojumper docs added, should be ready for merging. I suggest we don't delay that, since this PR has code that other stuff relies on (eg. #790,  #764 for the new version check infrastructure)

**Pull request merged**
