### PR TITLE
Fix issue with pillar ability's cover not updating properly on units spawned next to the actor 

### LINKED ISSUE #1288: Templars' Pillar doesn't give cover when spawned directly adjacent to units
Seems like an oversight, it works fine when you spawn a pillar and then move a unit to it, but if spawned right near a unit, it will not provide cover right away.

### PR DESCRIPTION
**Pull request by BlackDog86**
Fixes #1288

### CODE REVIEW

**Review by Iridar — CHANGES_REQUESTED** [review]
This PR is missing .x2proj change for X2Effect_Pillar.

**Comment by BlackDog86** [comment]
Should be done now

**Comment by Iridar** [comment]
Sorry, but it's in the wrong commit now. For PRs that add new files to Highlander, the first commit must have the new file and change to .x2proj file (it helps to restart modbuddy before making the commit so that changes actually apply to the .x2proj file), and the second commit should have the rest of the PR.

**Comment by BlackDog86** [comment]
Commits re-arranged

**Comment by BlackDog86** [comment]
Needs more work - issue was more complex than first thought

**Comment by Iridar** [comment]
In testing this PR doesn't actually fix the issue. The latest commit includes other things I tried, but none of them help either. I'm closing it for now, feel free to reopen later if a solution is found.

**Pull request closed without merging**
