### PR TITLE
Pull Request for issue #984

### PR DESCRIPTION
**Pull request by Mitzruti**
added eInvSlot_MZAux, eInvSlot_TemplateMaster, Changelog entry

### CODE REVIEW

**Comment by Iridar** [comment]
Changelog.md file is deprecated and no longer used, so you can remove those changes from your Pull Request.

**Review by Iridar — APPROVED** [review]

**Comment by Iridar** [comment]
Looks good to me. We'll have to add an entry to #137 once this is merged.

**Comment by pledbrook** [comment]
Shouldn't new inventory slots be documented in the highlander online manual?

**Comment by Iridar** [comment]
> Shouldn't new inventory slots be documented in the highlander online manual?

Perhaps we're ought to add inline docs for them at some point, but for now they're just tracked in #137.

**Pull request merged**
