### PR TITLE
Add hook to allow mods to override hit chance

### PR DESCRIPTION
**Pull request by pledbrook**
This change adds an 'OverrideFinalHitChance' event that allows mods to override the shot breakdown for abilities. This is necessary to implement the graze band for LW2, but could be used by others as well.

### CODE REVIEW

**Comment by pledbrook** [comment]
This shouldn't be merged until we can work out why the existence of this event trigger is causing an occasional, but reproducible hang/freeze in the game. Could be something else in LWOTC, but don't know yet.

**Comment by pledbrook** [comment]
I'll be replacing this implementation, probably with one that uses a delegate or array of delegates in place of the event hook. Firing an event in the `FinalizeHitChance()` function seems very occasionally to cause a hang, even if there are no listeners for the corresponding event. It seems to happen exclusively when a unit is undertaking a melee attack, such as with Rend or LW2's Fleche.

**Comment by pledbrook** [comment]
New implementation ready for review.

**Comment by pledbrook** [comment]
Is the new implementation OK with folks? It seems to work reliably now. May just need testing in beta.

**Comment by MrNiceUK** [comment]
Ok, but late now, and somewhat just an aesthetic thing, but would have preferred the array of delegates to be called `OverrideFinalizeHitChanceFns`, since `FinalizeHitChance()` is the name of the method whose behaviour being overridden...

**Pull request merged**
