### PR TITLE
Tactical game state cleanup Issue #178

### LINKED ISSUE #178: Cleanup Tactical Gamestate
Ported from LW2 code.

### PR DESCRIPTION
**Pull request by Danice123**
If somebody wants to do a review of this that would be great.

Closes #178

### CODE REVIEW

**Comment by Danice123** [comment]
Removed objects after a tactical game, so I think that its working.

**Comment by Xymanek** [comment]
@pledbrook I was looking through lwtoc's DLCInfo and found [this bit](https://github.com/long-war-2/lwotc/blob/1cf6feb6cd26f7e92edf9384459502d64cd0f7f0/LongWarOfTheChosen/Src/LW_Overhaul/Classes/X2DownloadableContentInfo_LongWarOfTheChosen.uc#L1085-L1153). Considering that it's a base game issue and not a lwtoc-specific one, it might make sense to fix it in CHL (eg. see this pr)

**Comment by pledbrook** [comment]
Looks like it does the same thing, yes. I don't feel qualified to approve the PR, though.

**Comment by Iridar** [comment]
Closing due to lack of attention, and I'm not convinced the proposed solution is necessarily the best.

**Pull request closed without merging**
