### PR TITLE
Issue #89 - Tick damage ignores shields

### PR DESCRIPTION
**Pull request by TNychka**
See issue #89. Acid/Burning/Poison now ignore shields. Currently, this is assumed to be a bug fix: It may be intentionally designed behavior.

Second question, when submitting this pull request I had to manually change the EOL to unix style from windows. Is there something configurable in modbuddy so that I don't need to do this? Thanks.

### CODE REVIEW

**Comment by robojumper** [comment]
It's a gameplay change, so I would want it guarded behind a config option.

**Comment by TNychka** [comment]
Can do

**Comment by TNychka** [comment]
Do not merge this pull request, still doing some testing

**Comment by TNychka** [comment]
Added config variables that default to false. Tested in game as functional. @robojumper PTAL

**Comment by robojumper** [comment]
Can you comment out the entries in `XComGameCore.ini`? This way, mods that enable this behavior don't need to care about config load order.

**Comment by TNychka** [comment]
Fixed it!

**Pull request merged**
