### PR TITLE
Add 'none' checks and other fixes to prevent log spam added by TLP (Issue #295)

### PR DESCRIPTION
**Pull request by Iridar**
Props to @robojumper for posting the detailed list of log warnings:

Marked by "x" are the ones that I fixed.
Marked by "?" are the ones I fixed, but my confidence level about added changes is low, and I would appreciate code review on them.
I have not attempted to fix the unmarked ones due to not knowing how to approach the existing code, and I'm probably not gonna fix them, unless I get some directions.

 * [x]  `Accessed None 'SCREENSTACK' XComGame.XComGameState_Item:OnCreation:0120`
 * [x]  `Accessed None 'Ability' XComGame.XGUnit:CreateVisualizer:05B8`
 * [x]  `Accessed None 'FactionState' XComGame.UIPersonnel_SoldierListItem:UpdateData:0BA1`
 * [x]  `Accessed None 'FactionState' XComGame.UISoldierHeader:???:???`
 * [x]  `Accessed None 'EmptyRef' XComGame.X2StrategyElement_DefaultStaffSlots:GetLocationDisplayStringDefault:0022`
 * [x]  `Accessed None 'StateObject_NewState' XComGame.X2Action:AddActionToVisualizationTree:01DF `
 * [x]  `Accessed None 'm_kEntity' XComGame.XGWeapon:Destroyed:000A`
 * [x]  `Accessed None 'ExistingItem' XComGame.XComGameState_LadderProgress:SwapItem:0102`
 * [x]  `Accessed None 'replacementItem' XComGame.UILadderUpgradeScreen:PopulateUpgradePanel:06AA `
 * [ ]  `Accessed None 'MoveBeginAction' XComGame.X2Action:CheckMoveActionForMatch:01FD`
 * [x]  `Accessed array 'Targets' out of bounds (0/0)  XComGame.UITacticalHUD:TargetHighestHitChanceEnemy:0377`
 * [x]  `Accessed array 'UITacticalHUD_Enemies_1.m_arrTargets' out of bounds (0/0) XComGame.UITacticalHUD_Enemies:GetSelectedEnemyStateObjectRef:003D`
 * [x]  `ScriptWarning: Accessed None 'BG' XComGame.UIImageChip:SetWidth:001D`
 * [x]  `Accessed None 'NavHelp' XComGame.UITLE_ChallengeModeMenu:UpdateNavHelp:0247`
 * [ ]  `Accessed None 'ChildPanels' XComGame.UITLE_ChallengeModeMenu:UpdateList:007D`
 * [?]  `Accessed None 'EquippedItem' XComGame.UITLE_SkirmishModeMenu:SetSoldierGear:06A4`
 * [?]  `Accessed None 'utilItems' XComGame.UITLE_SkirmishModeMenu:UpdateDataSoldierEquipment:0455`

### CODE REVIEW

**Comment by Xymanek** [comment]
Tracking issue: #295

Better compare: https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/compare/4c6ee0f...ee55e6d

**Comment by Iridar** [comment]
> should it be closed when this PR is merged?

Probably not, given this pr doesn't fix all of the logged errors, and as robojumper said, the list is likely incomplete.

**Comment by robojumper** [comment]
I don't think adding every single log spam fix to Bugfixes is useful, but I can't immediately think of a better way to document the fact that we do have that sort of fix. I'd be okay with removing documentation from this PR entirely.

**Comment by Iridar** [comment]
Per robojumper's request, I have removed inline docs and replaced them with simple comments with the issue number.

**Comment by Iridar** [comment]
I have rebased this PR onto the current master, fixed a couple more log spam issues, and self-reviewed a couple of previous fixes where I wasn't confident in them, and adjusted one of them. Waiting for a review and then merge now.

**Comment by Iridar** [comment]
By the way, is it not a problem that I'm adding TLE files to the source?

**Comment by robojumper** [comment]
As long as it's `XComGame` classes, it's all fine since these classes are shipped with WotC even when TLP is not installed.

**Pull request merged**
