### PR TITLE
Add eInv Slots to enable Soldiers to carry multiple unique Proximity-Activated Items for the Requiem Campaign

### PR DESCRIPTION
**Pull request by ReshiMael**
To conditionally allow or disallow Soldiers to equip one, or more, unique categories of Proximity-Activated Items.

### CODE REVIEW

**Comment by Iridar** [comment]
Do you specifically require two different inventory slots? Can your use case be satisfied with one multi-item slot?

**Comment by ReshiMael** [comment]
With a few tweaks to the use case I could stretch a multi-item slot to work for it.

**Comment by Iridar** [comment]
If possible, please try to get it done with one multi item slot, as there's a limited amount of new inventory slots we can add.

**Comment by ReshiMael** [comment]
Yeah, I can make one multi-item slot work.

**Comment by Iridar** [comment]
Alright, then please update the PR when you have everything implemented and working on your side, and add your inventory slot here: https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/issues/137

**Pull request merged**
