### PR TITLE
#560 feature/continuous-integration

### PR DESCRIPTION
**Pull request by abatewongc**
add build_jenkins.ps1
add tagmaker (tidecaller)
add jenkinsfile

Note: 
* maintainers may require more control over tidecaller
* still need credentials for x2communitycore

### CODE REVIEW

**Comment by pledbrook** [comment]
Is this a work in progress, or is it ready to merge?

**Comment by Xymanek** [comment]
More importantly: how is this supposed to work?

**Comment by abatewongc** [comment]
This is a WIP. I or some maintainer will need to go in and set up the project in both jenkins and github. Due to the nature of the project this probably shouldn't go into a milestone.

@Xymanek This will run a build for commits to master, create a tagged release, and upload a .zip of the release to Github. It can also run against other commits, although I'm hesistant to trust PRs.

**Comment by Xymanek** [comment]
Where would the builds be hosted though? Is there some free online jenkins SAAS?

**Comment by Xymanek** [comment]
Status update (based on discord conversation with author): this PR is intended to run on their homelab. However, the author indicated desire to withdraw from xcom2 modding scene and as such is no longer interested in maintaining this.

I, on the other hand, am planning to setup one soon, so this PR will be left for reference (for me or anyone else who plans to setup CI workflow)

**Comment by Iridar** [comment]
No offense, but it's been over a year. Perhaps, this PR can be a reference point while being closed?

**Comment by Xymanek** [comment]
Indeed, I haven't had time to setup my homelab (mainly due to working on CI in my free time).

Closing to avoid polluting the PR list since I doubt this will get any traction in close future

**Pull request closed without merging**
