### PR TITLE
Small improvements to #621 and #595 for 1.20.0 beta

### PR DESCRIPTION
**Pull request by Xymanek**
Private-d non-public-API functions from #621 
Fixed copy paste comment screw up in #595

### CODE REVIEW

**Comment by pledbrook** [comment]
Isn't this a breaking change now, at least the switch to `private`?

**Comment by Xymanek** [comment]
Well, this is awkward

**Comment by pledbrook** [comment]
I've set this to Waiting on Author since it seems like it's a breaking change, as I said. If it's not, happy to change it back. But it certainly shouldn't be Ready for Merge with this question mark hanging over it.

**Comment by robojumper** [comment]
Let's just go with this -- we can turn them `private` later if wanted.

**Pull request merged**
