### PR TITLE
Rework CHL Run Order

### PR DESCRIPTION
**Pull request by robojumper**
A commit with no real user-facing changes for now. Original DFS-based algorithm is kept intact, just enhanced with cycle checking and some less complex code (and better docs/var names).

Mod project with test config can be found at https://github.com/robojumper/CHLRunOrderTest

Checklist:

- [x] Finish mod dependency checking PR
- [x] Add user-facing error display?
- [x] Document feature

### CODE REVIEW

**Comment by robojumper** [comment]
Pinging -- again, sorry -- @Musashi1584 as the original author of this system.

**Comment by robojumper** [comment]
This is now based on #965 because I updated both PRs to ensure this doesn't crash the game if XComGame replacements aren't loaded. See 4fc7f16...6ffc0a5a for the actual changes.

**Comment by MrNiceUK** [comment]
Is the "run order" which results when cycles exist changed, or is the "enhancement" just notifying the user of the problem?

**Comment by robojumper** [comment]
This code should yield the same order that the original code created.

**Comment by robojumper** [comment]
Also going to merge this with the justification in <https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/pull/965#issuecomment-850903313>.

**Pull request merged**
