### PR TITLE
 Fire event on expiry of a dark event (#753)

### LINKED ISSUE #753: Fire an event when a dark event expires (is deactivated)
`XCGS_DarkEvent` has an `OnDeactivated()` function that's called when a dark event expires or is otherwise deactivated, but there is no easy way for mods to hook into this. The only solution I can think of is to wrap every Dark Event template's `OnDeactivatedFn` with a wrapper that does whatever the mod wants. This is a pretty obtuse solution to a problem that could be easily solved with a simple event fired at the end of `OnDeactivated()`.

One idea is to have a UI notification pop up when a dark event expires, but I'm sure there could be other features that would benefit from the hook.

### PR DESCRIPTION
**Pull request by pledbrook**
The `XCGS_DarkEvent.OnDeactivate()` function now fires a 'DarkEventDeactivated' event before deactivating the DE.

The event takes the form:
```
  ID: DarkEventDeactivated
  Data: self (XCGS_DarkEvent)
  Source: self (XCGS_DarkEvent)
  NewGameState: yes
```

Resolves #753.

### CODE REVIEW

**Comment by Xymanek** [comment]
I think I've said this before, I dislike events starting with `On[...]`/just stating the fact (this case is the latter) as it's unclear whether the vanilla behaviour has or has not happened yet, and this may be important for some consumers. A much better naming would be `Pre[...]`/`Post[...]`

**Comment by pledbrook** [comment]
Whether the vanilla behaviour has happened or not depends on what type of listener you set up, as described in the documentation for the event. So calling it `PreDarkEventDeactivated` would be inaccurate if you set up an `ELD_OnStateSubmitted` listener.

**Comment by Xymanek** [comment]
For `ELD_OnStateSubmitted` yes, but it does make a difference for `ELD_Immediate`

**Comment by pledbrook** [comment]
Event renamed.

**Pull request merged**
