### PR TITLE
Stop sounds when removing pawns

### LINKED ISSUE #1192: UIArmory.uc does not stop sounds or remove cosmetic units when removing pawns.
Pulling this conversation out of DMs and Iridar's discord.

Line 331 of UIArmory.uc:

```
simulated function ReleasePawn(optional bool bForce)
{
    Movie.Pres.GetUIPawnMgr().ReleasePawn(self, UnitReference.ObjectID, bForce);
    ActorPawn = none;
}
```

This function does not remove sounds, leading to persistent sounds being left behind, that are only removed by a save and reload.  This is most annoying when using something such as Kiruka's Playable Aliens for LWoTC, where the Archon's jet sound effect will be stuck in your squad select screen until you save/reload.

@RustyDios suggests updating the function to the below:

```
simulated function ReleasePawn(optional bool bForce)
{
    local XComUnitPawn CosmeticPawn;
    
    //destroy any gremlins
    CosmeticPawn = Movie.Pres.GetUIPawnMgr().GetCosmeticPawn(eInvSlot_SecondaryWeapon, UnitReference.ObjectID);
    if (CosmeticPawn != none)
    {    
        CosmeticPawn.StopSounds();
        Movie.Pres.GetUIPawnMgr().ReleasePawn(self, CosmeticPawn.ObjectID, bForce);
        CosmeticPawn = none;
    }

    ActorPawn.StopSounds();
    Movie.Pres.GetUIPawnMgr().ReleasePawn(self, UnitReference.ObjectID, bForce);
    ActorPawn = none;
}
```

### PR DESCRIPTION
**Pull request by Tedster59**
Fixes #1192

Remove sounds by updating DestroyPawns to call StopSounds() and Cosmetic Pawns from units by updating ReleasePawnInternal to grab and also remove the Cosmetic Pawn.  Addresses issue #1192 based on Rusty's code.

### CODE REVIEW

**Comment by Iridar** [comment]
If the first message in the PR has something like "Closes #1192" or "Fixes #1192", then the corresponding issue will be closed automatically when the PR is merged, so do that in the future, please.

**Comment by Iridar** [comment]
This generally looks like it should work, but it assumes the cosmetic unit comes from the secondary weapon slot. Do you think you can adjust the PR so it works regardless of slots?

**Comment by Tedster59** [comment]
Reworked this to loop over the attached units on the main pawn using its XCGS_Unit.  Also updated the documentation to better fit HL-Docs formatting.

**Comment by Tedster59** [comment]
Updated PR name to only address the stop sounds part, going to move the cosmetic stuff to a separate fix.

**Pull request merged**
