### PR TITLE
Fix missions with rescue rings (#551)

### PR DESCRIPTION
**Pull request by pledbrook**
In Gather Survivors and several LW2 missions, XCOM has to rescue units and
take them to evac. To enable player control of the rescued unit, its team
is swapped to XCom. But XGUnit then removes the range indicators from all
members of that unit's squad, which is not XCOM at that stage but team
Neutral.

This fix ensures that the swap team action changes the unit's squad (and
the pawn's team) in addition to the existing XGUnit team change.

### CODE REVIEW

**Comment by Xymanek** [comment]
What is the argument for/against using a config gate?

**Comment by pledbrook** [comment]
Argument for: this is a low-level change that could have unintended side effects. The config variable ensures that the player can pull out of the change if it breaks something in their game. Also, tracktwo and I are a bit nervous because we thought that Firaxis would have done this already when fixing the rescue rings for Gather Survivors. So perhaps the changes introduce other issues that couldn't be resolved? We just don't know.

Argument against: it's a bug fix, plain and simple. If it works without breaking anything else, it absolutely should not be gated behind a config variable.

So the config var is simply a defensive measure and not about giving players the option to play with one behaviour vs another.

**Comment by pledbrook** [comment]
I'm going to keep this as a draft PR until it's had some real field testing with LWOTC.

**Comment by pledbrook** [comment]
I haven't noticed any issues with this and it has been tested extensively in LWOTC now. Any argument against merging it into beta?

**Comment by Xymanek** [comment]
> we thought that Firaxis would have done this already when fixing the rescue rings for Gather Survivors

Did you test this in vanilla game?

**Comment by pledbrook** [comment]
In terms of whether the rescue rings remained in place? Pretty sure I did when I first created the fix.

**Comment by Xymanek** [comment]
Considering that 

* Rings in Gather Survivors are broken with vanilla XComGame
* If you save and reload right after, the pawn would be initialized with the values that this fix sets

I would argue for removing the config gate

**Comment by pledbrook** [comment]
@Xymanek Removed the config var guard.

**Pull request merged**
