### PR TITLE
#424 Add Greater Control for Gremlin "Ghosts" in Staffslots

### PR DESCRIPTION
**Pull request by VampireMonkey**
Should be fine now, if anybody has any problems with the changes in their games do tell.

### CODE REVIEW

**Comment by robojumper** [comment]
Please rebase your PR to

1. Not include UIPersonnel
2. Have one commit that adds all new files to the project (including the .x2proj file!)
3. Have one commit that actually makes your changes.

**Comment by VampireMonkey** [comment]
Ok i see i've been doing this wrong, i'll try to fix it

**Comment by Musashi1584** [comment]
the pull request is broken

**Comment by VampireMonkey** [comment]
I'll try to find time to fix it this weekend :s

**Comment by Xymanek** [comment]
Classes from `XComGame` package cannot use functions from classes in `X2WOTCCommunityHighlander` package

**Pull request closed without merging**
