### PR TITLE
Add UISquadSelect_NavHelpUpdate Event

### PR DESCRIPTION
**Pull request by Iridar**
Closes issue #420

### CODE REVIEW

**Comment by Iridar** [comment]
Briefly tested this with Prototype Armory, which listens to this event (expecting it from RJSS) to add a "remove weapon upgrades" button. Seems to work fine.

**Review by pledbrook — APPROVED** [review]
Looks good to me!

**Comment by Iridar** [comment]
One thing I'm not entirely sure about is that I have purposefully put the event trigger before `NavHelp.Show();`, so that any changes by mods are seamless. However, [in RJSS](https://github.com/Xymanek/robojumperSquadSelect/blob/5e066086e3ea3a054dc0d13a91df5c9f2d18cba9/robojumperSquadSelect/Src/robojumperSquadSelect/Classes/robojumper_UISquadSelect.uc#L852) there is no line like that in `UpdateNavHelp()` at all. So not sure what to make of it.

**Review by robojumper — APPROVED** [review]
Order of event and `Show()` shouldn't really matter; flash calls are queued and flushed at the end of the frame anyway.

**Pull request merged**
