### PR TITLE
Changed All IsPsiOperative to HasPsiGift in UISoldierHeader

### LINKED ISSUE #757: Change All IsPsiOperative to HasPsiGift in UISoldierHeader
Semi-related to #673 but not really, this change is possible and shouldn't break anything.

### PR DESCRIPTION
**Pull request by VampireMonkey**
Closes #757

### CODE REVIEW

**Comment by VampireMonkey** [comment]
dunno what iRank is or why it's there, i couldn't find it in the master or the fork files

**Comment by VampireMonkey** [comment]
Should be good now, i had to manually compare in another text editor.

**Comment by RealityMachina** [comment]
The game in its unmodded form doesn't assign `bHasPsiGift`. Maybe it should added as an either/or thing instead? 

e.g something like `if(Unit.IsPsiOperative() || Unit.HasPsiGift() )`

**Comment by pledbrook** [comment]
We can't be 100% certain that `HasPsiGift()` isn't being used in native code, nor do we understand what it's for if it is used. So it's unlikely we will merge this as it stands.

Perhaps if you explain the rationale, we can work out a more suitable solution.

**Comment by Iridar** [comment]
Closing due to author missing in action. Reopen if necessary. Refer to Issue #88 for further discussion on this Issue.

**Pull request closed without merging**
