### PR TITLE
Add More Generic Macros

### PR DESCRIPTION
**Pull request by VampireMonkey**
Like `XCOMHQ, but also `RESISTANCEHQ, `ALIENHQ and so on

### CODE REVIEW

**Comment by Xymanek** [comment]
Ummmm... the file is `Src/Core/Globals.uci` (not `Src/Globals.uci`)?

**Comment by VampireMonkey** [comment]
Can you move it? I can't make a new folder

**Comment by pledbrook** [comment]
Are there any issues with adding more entries to *Globals.uci*? Wondering if just moving the file will unblock this PR.

**Comment by VampireMonkey** [comment]
> Are there any issues with adding more entries to _Globals.uci_? Wondering if just moving the file will unblock this PR.

I can't see any problems with adding more entries

**Comment by Iridar** [comment]
Closing this PR, because it:
1. Wasn't fixed in nearly a year.
2. Doesn't have a tracking Issue. 
That said, I do support the idea of adding more macros, so I'm gonna open an Issue about that.

**Pull request closed without merging**
