### PR TITLE
Expand ability tags in Chosen strength/weakness text

### LINKED ISSUE #1096: Pass Chosen abilities descriptions through XEXPAND
Similar to what was done in #566 for sitreps description, can Chosen strengths/weakness descriptions get the same change? Namely, changing using AbilityTemplate.LocLongDescription to its expanded version. 
I believe it is needed in the following places:
UIChosenInfo - lines 150, 168;
UIChosenLevelUp - line 59;
UIChosenReveal - lines 55, 68.

### PR DESCRIPTION
**Pull request by pledbrook**
This modifies `UIChosenInfo` and `UIChosenReveal` so that they pass the strength and weakness descriptions for Chosen strengths through `ExpandString()`.

Fixes #1096.

### CODE REVIEW

**Review by Iridar — APPROVED** [review]

**Review by Xymanek — COMMENTED** [review]
Why
```uc
`XEXPAND.ExpandString(AbilityTemplate.LocLongDescription)
```
instead of
```uc
AbilityTemplate.GetMyLongDescription()
```
?

**Comment by Grobobobo** [comment]
I've changed it for him because peter's inactive.

**Review by Xymanek — CHANGES_REQUESTED** [review]
Please squash the last 2 commits (so there is 1 commit adding the files and 1 commit making the changes), otherwise approved

**Comment by Iridar** [comment]
Seeing as this hasn't moved in nearly a year, I went ahead and made the same PR with two commits instead of three.

https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/pull/1174

Closing this one.

**Pull request closed without merging**
