### PR TITLE
Remove all protectedwrites in XComGameState_EvacZone.uc

### PR DESCRIPTION
**Pull request by VampireMonkey**
There are 2, one for "TTile CenterLocation" and one for "ETeam Team", gets in the way.

### CODE REVIEW

**Comment by VampireMonkey** [comment]
Managed to create a new pull request when i just wanted the changelog entry to be added to this, it's all good now but the #1 link is incorrect, it's suppose to link to my fork pull request but instead it links to the #1 pull request on the main branch for some reason.

**Comment by Xymanek** [comment]
There is `SetCenterLocation()` function, why do you want to edit the variable directly?

**Comment by VampireMonkey** [comment]
Mainly i want to edit the Team, but might aswell make the other one non-protectedwrite while i'm at it

**Comment by Xymanek** [comment]
Could you explain your use case? I highly doubt the game supports changing evac zone's team after it was created

**Comment by VampireMonkey** [comment]
I'm making an Alien abilities mod, and one of the abilities places an EvacZone for the Aliens inside the ability's visualization block, problems start to happen with
```
	class'XComGameState_BattleData'.static.SetGlobalAbilityEnabled('Evac', true, NewGameState);

	`XEVENTMGR.TriggerEvent('EvacZonePlaced', EvacState, EvacState, NewGameState);
```
Basically i need to replace all the stuff `PlaceEvacZone` does with my own version, so that's why i need to change the Team variable without having it place the EvacZone for me.

Also `XComGameState_EvacZone` is a `XComGameState_BaseObject` so it can be changed like any other stateobject.

**Pull request closed without merging**
