### PR TITLE
Allow to equip Psi PCS on units with PsiOffense (#602)

### PR DESCRIPTION
**Pull request by boundir**
Changed `Unit.IsPsiOperative()` into `Unit.GetCurrentStat(eStat_PsiOffense) > 0` in `CanEquipImplant()`.

### CODE REVIEW

**Comment by pledbrook** [comment]
Please separate the addition of the UIInventory_Implant.uc and your change to it into separate commits.

**Comment by boundir** [comment]
Done. Is it ok this way?

**Comment by pledbrook** [comment]
Do you know how to rebase to remove the 96d8047 and e00d29d commits? Otherwise we could squash all the commits on merge, but that would defeat the purpose somewhat.

**Comment by boundir** [comment]
No. I will try to find out.

**Comment by boundir** [comment]
Clean PR here [#604](https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/pull/604) :)

**Pull request closed without merging**
