### PR TITLE
Create UISquadSelect.uc

### PR DESCRIPTION
**Pull request by john-luke-pack-hard**
Contains WotC's updated UISquadSelect.uc code and added insertions for PI's strip behavior configs.

### CODE REVIEW

**Comment by Musashi1584** [comment]
Please read https://github.com/X2CommunityCore/X2WOTCCommunityHighlander#documenting-your-contributions. Changes to the vanilla code should reference a issue. @john-luke-pack-hard 

AutoStripWoundedAllItems needs probably be revised when your custom slot patch is merged @robojumper

**Comment by Musashi1584** [comment]
Not sure if [Issue #161](https://github.com/X2CommunityCore/X2CommunityHighlander/issues/161) of the basegame highlander is also needed to complete the strip functionality. Probably not directlly related but maybe worth to have a look,

**Comment by john-luke-pack-hard** [comment]
https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/issues/134

Done, vars and clauses marked with issue number.

**Comment by Musashi1584** [comment]
Awesome thank you. To make you PR complete you could add a entry in the CHANGELOG.md documenting the changes. Saves @MalucoMarinero some time when merging all PRs.

**Comment by john-luke-pack-hard** [comment]
https://github.com/X2CommunityCore/X2WOTCCommunityHighlander/pull/135

I created another pull request because, forgive my ignorance, I don't know how to modify existing ones to encompass more holistic changes.

**Comment by MalucoMarinero** [comment]
@robojumper how long away is InventorySlot work? just wondering if I should hold off on this til it's ready or just bring it in.

**Pull request merged**
