### PR TITLE
Can override patrol destinations using LW tuple

### PR DESCRIPTION
**Pull request by RedDoby**
#718 
This feature allows mods to enable any alert cause to override the patrol locations for enemy groups. Had to add a new source file XComGameState_AIUnitData, changes start on line 128 and end on 164. 

I made a mistake and added the changed file X2WOTCCommunityHighlander/X2WOTCCommunityHighlander.x2proj to #1165. Can someone please move that here or simply approve both pull requests together?

#510 #619 Added docs

### CODE REVIEW

**Comment by Iridar** [comment]
When you add new files to Highlander's source, please have the new file being added and the change to the .x2proj file in one commit, and all changes you make to the newly added file in further commits. That way it's easier to tell what you have changed from the original.

**Comment by Iridar** [comment]
Also, something doesn't work about parsing your event docs, so you want to double check those, make sure they're formatted right. One thing to look into is checking whether you can have a comma after the last element in the data array.

**Comment by RedDoby** [comment]
> When you add new files to Highlander's source, please have the new file being added and the change to the .x2proj file in one commit, and all changes you make to the newly added file in further commits. That way it's easier to tell what you have changed from the original.

Do you need me to redo everything or are you referring to future pull requests?

**Comment by RedDoby** [comment]
> Also, something doesn't work about parsing your event docs, so you want to double check those, make sure they're formatted right. One thing to look into is checking whether you can have a comma after the last element in the data array.

It is fixed.

**Comment by Iridar** [comment]
> > When you add new files to Highlander's source, please have the new file being added and the change to the .x2proj file in one commit, and all changes you make to the newly added file in further commits. That way it's easier to tell what you have changed from the original.
> 
> Do you need me to redo everything or are you referring to future pull requests?

This aspect needs to be redone, sadly. Ideally, you should have 2 commits in this PR, one where you add a new file and the associated change to .x2proj file, and one where all your changes are added.

**Pull request closed without merging**
